import { describe, it, expect } from 'vitest'
import { parseEnvFile } from '../src/parser.js'
import { generateDts } from '../src/generator.js'

describe('generateDts', () => {
  it('generates required entry without ?', () => {
    const entries = parseEnvFile('PORT=3000')
    const dts = generateDts(entries)
    expect(dts).toContain('PORT: string')
    expect(dts).not.toContain('PORT?: string')
  })

  it('generates optional entry with ?', () => {
    const entries = parseEnvFile('OPTIONAL=')
    const dts = generateDts(entries)
    expect(dts).toContain('OPTIONAL?: string')
  })

  it('includes JSDoc description', () => {
    const entries = parseEnvFile('# Server port\nPORT=3000')
    const dts = generateDts(entries)
    expect(dts).toContain('Server port')
  })

  it('includes type hint for number', () => {
    const entries = parseEnvFile('PORT=3000')
    const dts = generateDts(entries, { typeHints: true })
    expect(dts).toContain('@type {number string}')
  })

  it('includes type hint for boolean', () => {
    const entries = parseEnvFile('DEBUG=true')
    const dts = generateDts(entries, { typeHints: true })
    expect(dts).toContain('"true" | "false"')
  })

  it('omits type hints when typeHints: false', () => {
    const entries = parseEnvFile('PORT=3000')
    const dts = generateDts(entries, { typeHints: false })
    expect(dts).not.toContain('@type')
  })

  it('wraps in NodeJS ProcessEnv namespace', () => {
    const dts = generateDts([])
    expect(dts).toContain('declare namespace NodeJS')
    expect(dts).toContain('interface ProcessEnv')
  })

  it('includes auto-generation banner', () => {
    const dts = generateDts([])
    expect(dts).toContain('Auto-generated by env-types')
  })

  it('uses custom banner when provided', () => {
    const dts = generateDts([], { banner: '// My custom banner' })
    expect(dts).toContain('My custom banner')
    expect(dts).not.toContain('Auto-generated')
  })

  it('ends with a newline', () => {
    const dts = generateDts([])
    expect(dts.endsWith('\n')).toBe(true)
  })

  it('generates valid .d.ts for a realistic .env.example', () => {
    const content = `
# App config
NODE_ENV=development
PORT=3000

# Database
DATABASE_URL=postgres://localhost:5432/mydb

# Optional
SENTRY_DSN=
`.trim()
    const entries = parseEnvFile(content)
    const dts = generateDts(entries)

    expect(dts).toContain('NODE_ENV: string')
    expect(dts).toContain('PORT: string')
    expect(dts).toContain('DATABASE_URL: string')
    expect(dts).toContain('SENTRY_DSN?: string')
  })
})
