import type { EnvEntry, InferredType } from './parser.js'

export interface GenerateOptions {
  /** Prepend this banner comment. Defaults to standard "do not edit" notice. */
  banner?: string
  /**
   * When true, add a JSDoc `@type` hint showing the inferred primitive type
   * alongside the variable name. Default: true.
   */
  typeHints?: boolean
}

const TYPE_HINT: Record<InferredType, string> = {
  string: 'string',
  number: 'number string',
  boolean: '"true" | "false"',
  url: 'URL string',
  json: 'JSON string',
}

const DEFAULT_BANNER = `\
// Auto-generated by env-types — do not edit manually.
// Source: .env.example  |  Regenerate: npx env-types generate`

// Escape end-of-block-comment sequences so a description from the .env file
// can't prematurely close the generated JSDoc block and break the .d.ts.
function escapeJsDoc(text: string): string {
  return text.replace(/\*\//g, '*\\/')
}

/**
 * Produce a `ProcessEnv` augmentation `.d.ts` from parsed env entries.
 *
 * Variables with a non-empty value → required (`VAR: string`)
 * Variables with an empty value    → optional (`VAR?: string`)
 */
export function generateDts(
  entries: EnvEntry[],
  options: GenerateOptions = {},
): string {
  const banner = options.banner ?? DEFAULT_BANNER
  const typeHints = options.typeHints ?? true
  const lines: string[] = [banner, '', 'declare namespace NodeJS {', '  interface ProcessEnv {']

  for (const entry of entries) {
    const docParts: string[] = []

    if (entry.description) docParts.push(escapeJsDoc(entry.description))
    if (typeHints && entry.inferredType !== 'string') {
      docParts.push(`@type {${TYPE_HINT[entry.inferredType]}}`)
    }
    if (entry.isOptional) docParts.push('@optional')

    if (docParts.length > 0) {
      if (docParts.length === 1) {
        lines.push(`    /** ${docParts[0]} */`)
      } else {
        lines.push('    /**')
        for (const part of docParts) {
          lines.push(`     * ${part}`)
        }
        lines.push('     */')
      }
    }

    const opt = entry.isOptional ? '?' : ''
    lines.push(`    ${entry.key}${opt}: string`)
  }

  lines.push('  }', '}', '')
  return lines.join('\n')
}

/**
 * Produce a typed `env` object literal that consumers can paste into their
 * project as a starting point for a manual schema — useful when migrating
 * from auto-generated types to a validated schema.
 */
export function generateSchema(entries: EnvEntry[]): string {
  const lines: string[] = [
    '// Scaffold generated by env-types. Adjust types and add validation as needed.',
    "import { loadEnv } from '@the-arj/env-types'",
    '',
    'export const env = loadEnv({',
  ]

  for (const entry of entries) {
    const type = entry.inferredType
    const required = !entry.isOptional
    // `//` line comments don't need JSDoc escaping, but strip any newlines
    // defensively since descriptions come from a single .env comment line.
    const comment = entry.description ? `  // ${entry.description.replace(/\r?\n/g, ' ')}` : ''
    if (comment) lines.push(comment)
    lines.push(
      `  ${entry.key}: { type: '${type}'${required ? '' : ", required: false"} },`,
    )
  }

  lines.push('})', '')
  return lines.join('\n')
}
